### ISSUE TITLE
Function replacement

### ISSUE THREAD

**Issue by dDeepLb** [Eddiidev/ELA#1]
https://github.com/Eddiidev/ELA/blob/eed5d3d9a6961f2bba81dd36900b897afbc04fba/script.js#L476-L477 should be replaced with
```js
Player.ExtensionSettings.ELA = JSON.stringify(settings);
ServerPlayerExtensionSettingsSync("ELA");
```
for more reliable data saving

**Comment by Eddiidev** [comment]
Absolutely! I've updated it to use the appropriate function, works great, thanks for the heads-up!
https://github.com/Eddiidev/ELA/commit/0cdaac3aedd6fb04ecd0ee801bcfe8a9ebd802f1
